---
stack_name: ExampleStack                      # The stack name will be prepended to all other resource names
domain: example.com                           # The top level domain to be used
subdomain: mysubdomain                        # The subdomain this site will be deployed under
acm_id: 04fb379c-6873-45b5-9277-4ad37d61365e  # The ID of the AWS Certificate Manager certificate to use
source: ../src
